version: "0.2"
user: sam.shar99
key: uVFcrGeLUwYBUAYkiyA6auIXYPW0YZNlHGdT2gYPsIztDyq3j0
testSuites: []
preDirectives:
    commands: []
    maxRetries: 0
    shell: ""
    workingDirectory: ""
postDirectives:
    commands: []
    shell: ""
    workingDirectory: ""
jobLabel:
    - HyperExecute
    - XCUI
    - Real Device
runson: ios
autosplit: true
concurrency: 2
testDiscoveryResult:
    - LaunchTests/test_7
    - ClassA/test_1
    - ClassA/test_2
    - ClassA/test_3
    - ClassB/test_4
    - ClassB/test_5
    - ClassB/test_6
testDiscoveryResult2D:
    - - LaunchTests/test_7
    - - ClassA/test_1
    - - ClassA/test_2
    - - ClassA/test_3
    - - ClassB/test_4
    - - ClassB/test_5
    - - ClassB/test_6
tunnelOpts:
    testsPerTunnel: 10
retryOnFailure: true
maxRetries: 2
jobID: 2c5f3d62-78ac-42f9-8f79-4c833f68f3c2
codeDirectory: LambdaTestiOSDemo
framework:
    name: ios/xcui
    flags: []
    discoveryFlags: []
    discoveryType: ""
    runnerFlags: []
    workingDirectory: ""
    isTestNGXMLSuite: false
    defaultReports: false
    args:
        appPath: AppsToTest-rdc/LambdaTestiOSDemo.ipa
        testSuitePath: AppsToTest-rdc/LambdaTestiOSDemoUITests-Runner.ipa
        xcTestPlanPath: ""
        shards:
            mappings: []
        filters:
            attributes: []
        devices:
            - .*-16
        deviceSelectionStrategy: any
        appId: lt://APP10160161211712778173027784
        testSuiteAppId: lt://APP10160241051712778173410736
        xcTestPlanId: ""
        video: true
        deviceLog: true
        buildName: ""
        globalHttpProxy: true
        skipXMLOnRun: false
        skipInstall: false
        disableReleaseDevice: false
        platformName: ""
        isRealMobile: false
        avoidAppLaunch: false
        queueTimeout: 0
        uninstallPreviousBuild: false
        language: ""
        locale: ""
        preservedDevice: false
        fixedIP: ""
        resignApp: true
        minorOsVersion: false
        playwrightRD: false
        mobileDC: true
        skipUninstallPreviousBuild: false
        isVirtualDevice: false
    additional_args: null
    licenseKey: ""
    userdefinediscovery: false
    toscaArgs: null
    version: ""
    downloadURL: ""
    baseCommand: ""
cypress: false
betaFeature:
    setPartiallyCompletedAsCompleted: false
testType: ios/xcui
combineTasksInMatrixMode: false
captureScreenRecordingForScenarios: false
maxRetriesPreSteps: 0
triggerMode: true
sourcePayload:
    platform: realDevice
    verifySSL: true
collectLocalGitData: true
dynamicAllocation: false
appium: false
platformConfig: null
differentialUpload:
    enabled: false
    ttlHours: null
    forcedDisabled: false
project:
    id: ""
    name: ""
    type: default
meta: {}
alwaysRunPostSteps: false
errorCategorizedOnFailureOnly: false
storageType: ""
