name: LambdaTest Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-14

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.2

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare test build
        run: |
          chmod +x prepareTestBuild-rdc.sh
          ./prepareTestBuild-rdc.sh

      - name: List generated files
        run: |
          ls -R

      - name: Run LambdaTest tests
        run: |
          ./runLambdaTest.sh
        env:
          LT_USERNAME: ${{secrets.LT_USERNAME}}
          LT_ACCESS_KEY: ${{secrets.LT_ACCESS_KEY}}
